# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e540234306fa7bf07bc16b73059fb98b5ebe293b8a8df3d41130bc939ee561301ececb01537c4bdea073a5c56e97bb8b518e38f2541517e6f42686ad516ccd8b

test:
  secret_key_base: bcea416dcc59a70f72945474e4a4a94b6249ed6c9ede6800a363f9dcc03ed9319614c9b96ef4560ecec76b47bed5796caa678e144f80c32d08b735475d8bc24c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
